USE [master]
GO

/****** Object:  Database [RealEstateRental]    Script Date: 08.04.2026 1:57:53 ******/
CREATE DATABASE [RealEstateRental]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RealEstateRental', FILENAME = N'C:\Users\Дмитрий\RealEstateRental.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'RealEstateRental_log', FILENAME = N'C:\Users\Дмитрий\RealEstateRental_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RealEstateRental].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RealEstateRental] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RealEstateRental] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RealEstateRental] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RealEstateRental] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RealEstateRental] SET ARITHABORT OFF 
GO

ALTER DATABASE [RealEstateRental] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [RealEstateRental] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RealEstateRental] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RealEstateRental] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RealEstateRental] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RealEstateRental] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RealEstateRental] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RealEstateRental] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RealEstateRental] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RealEstateRental] SET  ENABLE_BROKER 
GO

ALTER DATABASE [RealEstateRental] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RealEstateRental] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RealEstateRental] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RealEstateRental] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RealEstateRental] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RealEstateRental] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RealEstateRental] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RealEstateRental] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [RealEstateRental] SET  MULTI_USER 
GO

ALTER DATABASE [RealEstateRental] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RealEstateRental] SET DB_CHAINING OFF 
GO

ALTER DATABASE [RealEstateRental] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [RealEstateRental] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [RealEstateRental] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [RealEstateRental] SET OPTIMIZED_LOCKING = OFF 
GO

ALTER DATABASE [RealEstateRental] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [RealEstateRental] SET QUERY_STORE = ON
GO

ALTER DATABASE [RealEstateRental] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [RealEstateRental] SET  READ_WRITE 
GO

